#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Redirects to another page

# Update package information and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a default Hello World page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Create a new Nginx configuration file for redirection
sudo tee /etc/nginx/sites-available/redirect_me > /dev/null <<EOL
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        # Your existing location configuration
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Create a symbolic link to enable the new configuration
sudo ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart

echo "Nginx has been configured for redirection. /redirect_me now redirects to https://www.youtube.com/watch?v=QH2-TGUlwu4."