#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header.

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file
CONFIG_FILE="/etc/nginx/sites-available/default"

# Add a custom header to the configuration
echo "add_header X-Served-By \$hostname;" | sudo tee -a $CONFIG_FILE

# Reload Nginx to apply changes
sudo service nginx reload
