#!/usr/bin/env bash
# Installs, configures, and starts the load balancer

set -e

# Update system and install prerequisites
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common

# Add HAProxy repository and install HAProxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Load balancer configuration
DOMAIN_NAME='DevBasem.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
    balance roundrobin
    server 914-web-01 34.138.32.248:80 check
    server 914-web-02 3.226.74.205:80 check
frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

# Ensure configuration files exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Enable HAProxy in init file
if ! grep -q '^ENABLED=[01]$' "$INIT_FILE"; then
    echo 'ENABLED=1' >> "$INIT_FILE"
fi

# Update HAProxy configuration
CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < "$CONFIG_FILE")
start_tkn="#--$DOMAIN_NAME-params-begin--"
end_tkn="#--$DOMAIN_NAME-params-end--"

if [ "$CONFIG_WORDS" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"
else
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"
fi

# Restart HAProxy service
if pgrep -x haproxy > /dev/null; then
    sudo service haproxy restart
else
    sudo service haproxy start
fi
