#!/usr/bin/env bash
# Install and configure HAProxy for load balancing web servers

# Update the package index
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Create a backup of the default configuration (optional)
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
defaults
    mode http
    timeout connect 5s
    timeout client 50s
    timeout server 50s

frontend web_frontend
    bind *:80
    mode http
    timeout client 1m
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    timeout server 1m
    server 502382-web-01 54.157.152.252:80 check
    server 502382-web-02 54.82.119.92:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy.service

# Enable HAProxy to start on boot
sudo systemctl enable haproxy.service

# Display HAProxy status
sudo systemctl status haproxy.service
