#!/usr/bin/env bash
# 100-process_and_pid_file script

handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    echo "Cleaning up and exiting"
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals and call corresponding functions
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Save PID to the file /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
