#!/usr/bin/env bash
# 101-manage_my_process script

MANAGE_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

start_manage_my_process() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already started."
    else
        $MANAGE_SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
    fi
}

stop_manage_my_process() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart_manage_my_process() {
    stop_manage_my_process
    start_manage_my_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_manage_my_process
        ;;
    stop)
        stop_manage_my_process
        ;;
    restart)
        restart_manage_my_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
