#!/usr/bin/env bash
# 7-highlander script

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Infinite loop with a sleep of 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done
