#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

hour=0
while [ "$hour" -lt 12 ]; do
    echo "Hour: $hour"
    
    minute=1
    while [ "$minute" -lt 60 ]; do
        echo "$minute"
        ((minute++))
        if [ "$minute" -eq 60 ]; then
            break
        fi
    done
    
    ((hour++))
done

