#!/usr/bin/env bash
# Check information about the school file

file_path="school"

if [ -e "$file_path" ]; then
    echo "school file exists"

    if [ -f "$file_path" ]; then
        echo "school is a regular file"

        if [ -s "$file_path" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    else
        echo "school is not a regular file"
    fi
fi
