#!/usr/bin/env bash
# Find the PID of the Gunicorn master process

MASTER_PID=$(pgrep gunicorn)

if [[ -z $MASTER_PID ]]; then
    echo "Gunicorn is not running."
    exit 1
fi

kill -s SIGHUP "$MASTER_PID"

echo "Gunicorn reloaded gracefully."
