#!/usr/bin/env bash
# This script creates an RSA key pair with the name "school" and a passphrase "betty"

# Check if the key pair already exists
if [[ -e ~/.ssh/school ]]; then
    echo "Key pair 'school' already exists."
else
    # Generate the RSA key pair
    ssh-keygen -t rsa -b 4096 -P betty -f school
fi